version: '3.7'

services:
  # PHP Service
  php-fpm:
    build: ./.docker/php
    container_name: sanctum-auth-php
    labels:
      - php
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
    volumes:
      - .:/var/www
    networks:
      - sanctum-auth-network

  # Nginx Server
  nginx:
    build: ./.docker/nginx
    container_name: sanctum-auth-nginx
    labels:
      - webserver
    depends_on:
      - php-fpm
    volumes:
      - ./.docker/nginx/:/etc/nginx/conf.d
      - .:/var/www
    ports:
      - 80:80
    networks:
      - sanctum-auth-network

  # MySQL Service
  mysql:
    build: .docker/mysql
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    container_name: sanctum-auth-mysql
    restart: always
    tty: true
    ports:
      - "33008:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      - ./.docker/mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - sanctum-auth-network

# Docker Networks
networks:
  sanctum-auth-network:
    driver: bridge
